### PR TITLE
Fix input from pipe

### LINKED ISSUE #95: Not able to run loophole inside a script
**Describe the bug**

The following issues was reported:

> I am trying out loophole which is working perfectly fine when I run it from command line. However when I try to run it from a > shell script (using the same command) It throws this error -

```
{"level":"fatal","error":"inappropriate ioctl for device","time":"2021-01-29T23:05:57+05:30","message":"Error saving terminal state"}
```

**To Reproduce**

TODO

**Expected behavior**

The loophole command works the same way inside a script and on standard command line.

**Screenshots**

TODO

**Environment**

TODO

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by denny241**
Closes #95 
Still want to clean it up a little before we merge it and haven't had time to test it properly yet, but the first commit should contain everything that is needed to fix the issue.

### CODE REVIEW

**Comment by denny241** [comment]
Should be good now. 
I put the IsPipe() function into the closehandler package, but if you can think of a better spot to put it or if you think this is a good chance to make something like a utils pkg, let me know.

File: cmd/virtual-serve.go [hunk 1]
```diff
@@ -56,14 +60,29 @@ func parseBasicAuthFlags(flagset *pflag.FlagSet) error {
...
+			}
+			fmt.Println()
+		} else {
+			reader := bufio.NewReader(os.Stdin)
+			passwordBytes, err := reader.ReadBytes('\n')
+			//if the reader encounters EOF before \n,
+			//we assume that everything up until EOF is the intended password and continue
+			if err != nil && err != io.EOF {
+				communication.Warn("An error occured while reading the basic auth password from pipe.")
+				communication.Warn(err.Error())
```
Comment (0x7f) [inline cmd/virtual-serve.go:80]: Does it make sense to continue in case we run into an error here? Or shall the program exit with some non-zero code?

File: internal/pkg/closehandler/closehandler.go [hunk 2]
```diff
@@ -14,14 +14,18 @@ var terminalState *terminal.State = &terminal.State{}
...
-		communication.Warn("Error saving terminal state")
-		communication.Warn(err.Error())
-	}
 
+	if !IsPipe() { //don't try to get terminal state if using a pipe
+		var err error
+		terminalState, err = terminal.GetState(int(os.Stdin.Fd()))
+		if err != nil {
+			communication.Warn("Error saving terminal state")
+			communication.Warn(err.Error())
```
Comment (0x7f) [inline internal/pkg/closehandler/closehandler.go:26]: Same here. I guess the value for `terminalState` is undefined and we should not try reading it in case there is an error.

File: internal/pkg/closehandler/closehandler.go [hunk 3]
```diff
@@ -31,3 +35,13 @@ func SetupCloseHandler(feedbackFormURL string) {
 		os.Exit(0)
 	}()
 }
+
+//IsPipe returns whether a pipe is being used for inputs or not
+func IsPipe() bool {
+	stdinInfo, err := os.Stdin.Stat()
+	if err != nil {
+		communication.Warn("Error getting terminal info")
+		communication.Warn(err.Error())
```
Comment (0x7f) [inline internal/pkg/closehandler/closehandler.go:44]: Same here.

**Review by 0x7f — APPROVED** [review]
LGTM. I would just change the error paths and exit the program right away.

File: cmd/virtual-serve.go (hunk 1 above)
Comment (Morishiri) [reply cmd/virtual-serve.go:80]: I think that's exactly what makes it work in scripts :P Because it was not able to obtain `terminalState` correctly then and we can ignore it as `terminalState` is only used to display things, am I right @denny241 ?

**Review by Morishiri — CHANGES_REQUESTED** [review]

File: internal/pkg/closehandler/closehandler.go [hunk 4]
```diff
@@ -14,14 +14,18 @@ var terminalState *terminal.State = &terminal.State{}
 
 // SetupCloseHandler ensures that CTRL+C inputs are properly processed, restoring the terminal state from not displaying entered characters where necessary
 func SetupCloseHandler(feedbackFormURL string) {
+	var terminalState *terminal.State
```
Comment (Morishiri) [inline internal/pkg/closehandler/closehandler.go:17]: Additionally https://pkg.go.dev/golang.org/x/crypto/ssh/terminal says ```Deprecated: this package moved to golang.org/x/term.```

We should refactor it to use https://pkg.go.dev/golang.org/x/term.

Comment (Morishiri) [reply internal/pkg/closehandler/closehandler.go:17]: May be a separate PR.

Comment (denny241) [reply internal/pkg/closehandler/closehandler.go:18]: will open a separate PR for it

**Review by 0x7f — APPROVED** [review]

**Review by Morishiri — APPROVED** [review]
