### PR TITLE
Move closehandler to pkg, move feedback form to closehandler

### LINKED ISSUE #71: Terminal is stuck after using CTRL-C when prompted for password
**Describe the bug**
Terminal is stuck after using CTRL-C when prompted for password. It is not displaying what user is typing.

It happens in two places:
1. When setting up a tunnel with only `--basic-auth-username` provided
2. When using ssh key with password protection (without ssh-agent)

**To Reproduce**
1. Start one of the actions above
2. Use CTRL-C to cancel input
3. Learn that your terminal no longer displays what you're typing.

**Expected behavior**
It should not break user terminal

**Screenshots**
N/A

**Environment**
 - OS: Linux
 - Version: master

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by denny241**
Closes #71 

There is still a bug where several instances of "Goodbye" will be printed at the end because a separate closehandler seems to be needed for every pkg inside of which the user might press CTRL+C; a way of closing the closehandler without closing the program is the next step

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -29,8 +29,6 @@ var rootCmd = &cobra.Command{
 func init() {
 	cobra.OnInitialize(initLogger)
 
-	displayOptions.FeedbackFormURL = "https://forms.gle/K9ga7FZB3deaffnV7"
```
Comment (Morishiri) [inline cmd/root.go:32]: Would that be possible to leave it here and pass displayOptions to closehandler?

File: internal/app/loophole/loophole.go [hunk 2]
```diff
@@ -240,8 +218,9 @@ func listenOnRemoteEndpoint(serverSSHConnHTTPS *ssh.Client) net.Listener {
 	return listenerHTTPSOverSSH
 }
 
+//ForwardPort takes care of exposing local HTTP ports via a reverse proxy
 func ForwardPort(config lm.ExposeHttpConfig) {
-	setupCloseHandler(config.Display.FeedbackFormURL)
+	closehandler.SetupCloseHandler()
```
Comment (Morishiri) [inline internal/app/loophole/loophole.go:223]: what if you would set it up in the commands only? E.g. in each relevant `Run` method, or even `PreRun`? I think it should then not duplicate the output and should be enough to fix ctrl c breaking temrinal

Comment (denny241) [reply internal/app/loophole/loophole.go]: I don't remember why I thought that it needs to be setup in every command separately, after some testing I just moved it to the init of the root command and it worked for both ssh and basic auth.

File: internal/pkg/closehandler/closehandler.go [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+		communication.PrintGoodbyeMessage()
+		if successfulConnectionOccured {
+			communication.PrintFeedbackMessage(feedbackFormURL)
+		}
+		os.Exit(0)
+	}()
+}
+
+//SuccessfulConnectionOccured sets the corresponding boolean to true, enabling the display of the feedback form URL after closing the CLI
+func SuccessfulConnectionOccured() {
```
Comment (Morishiri) [inline internal/pkg/closehandler/closehandler.go:39]: maybe `MarkConnectionSuccessful` instead?

**Review by Morishiri — APPROVED** [review]
