### PR TITLE
Longer Outage Reconnect fix

### LINKED ISSUE #48: Reconnect only works for short outages
**Describe the bug**
Reconnect only works for short outages, if it's longer and fails to reconnect it throws errors

**To Reproduce**
1. Establish tunnel
2. Kill the gateway for longer (contact me for instructions how to do it)

**Expected behavior**
It should try few times in a period of ~5 seconds and then close completely.

**Screenshots**
Screenshot from 2020-10-22 18-08-31

**Environment**
 - OS: Linux
 - Browser: n/a
 - Version: 1.0.0-beta.5

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by denny241**
Closes #48

### CODE REVIEW

File: internal/app/loophole/loophole.go [hunk 1]
```diff
@@ -201,23 +201,35 @@ func generateListener(config lm.Config, publicKeyAuthMethod *ssh.AuthMethod, pub
...
 		el.Msg("Dialing gateway to establish the tunnel..")
 	}
-	serverSSHConnHTTPS, err := ssh.Dial("tcp", config.GatewayEndpoint.String(), sshConfigHTTPS)
-	if err != nil {
-		loadingFailure(loader)
-		fmt.Fprintln(colorableOutput, aurora.BgRed("An error occured while dialing into SSH. If your connection has been running for a while, this might be caused by the server shutting down your connection."))
+
+	var sshSuccess bool = false
+	var sshRetries int = 5
+	for i := 0; i < sshRetries && sshSuccess == false; i++ { //Connection retries in case of reconnect during gateway shutdown
```
Comment (Morishiri) [inline internal/app/loophole/loophole.go:220]: !sshSuccess

File: internal/app/loophole/loophole.go [hunk 2]
```diff
@@ -201,23 +201,35 @@ func generateListener(config lm.Config, publicKeyAuthMethod *ssh.AuthMethod, pub
...
+		startLoading(loader, "Initializing secure tunnel... ")
+		serverSSHConnHTTPS, err = ssh.Dial("tcp", config.GatewayEndpoint.String(), sshConfigHTTPS)
+		if err != nil {
+			loadingFailure(loader)
+			log.Info().Msg("SSH Connection failed, retrying in 10 seconds... (Attempt " + strconv.Itoa(i+1) + "/" + strconv.Itoa(sshRetries) + ")")
```
Comment (Morishiri) [inline internal/app/loophole/loophole.go:225]: Can you please use `fmt.Sprintf`?

File: internal/app/loophole/loophole.go [hunk 3]
```diff
@@ -201,23 +201,35 @@ func generateListener(config lm.Config, publicKeyAuthMethod *ssh.AuthMethod, pub
...
+			time.Sleep(10 * time.Second)
+		} else {
+			sshSuccess = true
+		}
+	}
+	if sshSuccess == false {
```
Comment (Morishiri) [inline internal/app/loophole/loophole.go:231]: `!sshSuccess`

**Review by Morishiri — APPROVED** [review]
